### ISSUE TITLE
Błąd w sprawdzaczce turniejowej w grze "Dżungla"

### ISSUE THREAD

**Issue by Bozydarek** [janchorowski/ai_validator#10]
Sytuacja na planszy:
```
    0123456
0 | L #@#  
1 |    #   
2 |  DJ WC 
3 |  ~~ ~r 
4 | t~~ ~~ 
5 |  R~ ~~T
6 |  cw jd 
7 |    #   
8 |   #@# l
```

Ruch wykonują "małe" figury:
P0 -> S: `IDO 0 4 3 4`
Tzn. **t** z pozycji (0 4) na (3 4)
Natomiast sprawdzaczka rzuca wyjątek ponieważ według niej Tygrys powinien wylądować na polu (2 4):
```... ((0, 4), (0, 5)), ((0, 4), (2, 4)), ((0, 4), (0, 3)), ... ```

> The lion and tiger pieces may jump over a river by moving horizontally or vertically. They move from a square on one edge of the river to the next non-water square on the other side. [...]
> ~ from wikipedia.org

Po ruchu powinno być:
```
    0123456
0 | L #@#  
1 |    #   
2 |  DJ WC 
3 |  ~~ ~r 
4 |  ~~t~~ 
5 |  R~ ~~T
6 |  cw jd 
7 |    #   
8 |   #@# l
```

**Comment by janchorowski** [comment]
Poprawione w #11
